### ISSUE TITLE
Pure data ddsp~ external not found

### ISSUE THREAD

**Issue by moiseshorta** [acids-ircam/ddsp_pytorch#10]
Hi,

I've successfully built the realtime ddsp~ external for Linux, but it seems I'm having major trouble with pure data finding the external...

When I built, I generated a file called `ddsp~.pd_linux`, with a rough size of 93.2Kb. I've added this to the `ddsp_tilde` folder provided in the repo and then moved said folder to where my externals should be found...

I'm wondering if there's any step I'm missing and if you would be so kind as to provide some help.

EDIT: I have managed to find the external but I am getting a crash of Pure Data every time I try and run it. I'm posting here my log from building. I am using Linux Ubuntu 18.04:

`-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Caffe2: CUDA detected: 9.1
-- Caffe2: CUDA nvcc is: /usr/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr
-- Caffe2: Header version is: 9.1
-- Found cuDNN: v7.6.0  (include: /home/hexorcismos/anaconda3/include, library: /home/hexorcismos/anaconda3/lib/libcudnn.so)
-- Autodetected CUDA architecture(s):  6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
-- Configuring done
CMake Warning at CMakeLists.txt:18 (add_library):
  Cannot generate a safe runtime search path for target ddsp_tilde because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libnvToolsExt.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/hexorcismos/anaconda3/lib

  Some of these libraries may not be found correctly.

CMake Warning at CMakeLists.txt:18 (add_library):
  Cannot generate a safe runtime search path for target ddsp_tilde because
  there is a cycle in the constraint graph:

    dir 0 is [/home/hexorcismos/anaconda3/lib/python3.7/site-packages/torch/lib]
      dir 1 must precede it due to runtime library [libc10.so]
    dir 1 is [/home/hexorcismos/anaconda3/lib/python3.7/site-packages/libtorch/lib]
      dir 0 must precede it due to runtime library [libtorch.so]
    dir 2 is [/home/hexorcismos/anaconda3/lib]

  Some of these libraries may not be found correctly.

-- Generating done
-- Build files have been written to: /home/hexorcismos/Desktop/AI/ddsp_pytorch/realtime/build
(ddsp_pt) (base) hexorcismos@DeepDisk:~/Desktop/AI/ddsp_pytorch/realtime/build$ make
Scanning dependencies of target ddsp_tilde
[ 33%] Building CXX object CMakeFiles/ddsp_tilde.dir/ddsp_tilde/ddsp_tilde.cpp.o
[ 66%] Building CXX object CMakeFiles/ddsp_tilde.dir/ddsp_tilde/ddsp_model.cpp.o
[100%] Linking CXX shared library "ddsp~.pd_linux"
[100%] Built target ddsp_tilde
`

Thanks so much in advance.

**Comment by caillonantoine** [comment]
Are you trying to build the external with CUDA enabled?

**Comment by moih** [comment]
I both tried it with Linux and OS X. On Linux I believe with CUDA enabled and OS X not.

Linux fails to detect the external at all, even when pointing at it with the 'declare -path'.

On OS X, the external does get detected by I get an error when trying to load your provided pre-trained model: 'error when importing model'

Any thoughts? Thanks in advance.

**Comment by caillonantoine** [comment]
It looks like you are using pytorch from an anaconda installation ! Make sure you are using the last version (>= 1.7) of  **libtorch** and not **pytorch**, you can download the library from the pytorch website (in CPU mode). Then recompile the external, put it somewhere Pd can see it.

You can also test the torchscript model with **pytorch** using the `performance.py` script to make sure its working.

```bash
python performance.py --model /path/to/pretrained.ts
```

But again, make sure you have the latest version, since I'm using one of pytorch's latest features !

**Comment by caillonantoine** [comment]
I've also updated the external so when there is an `model loading error` the complete error is posted on Pd's console !

**Comment by caillonantoine** [comment]
Be sure to update pytorch to a version >= 1.7 ! I've also modified the external so that any `model loading error` is entirely posted to Pd's console. For the linux version, maybe try to download a CPU only version of libtorch.

**Comment by moiseshorta** [comment]
It is working now! I am now having another problem, but with the train.py script, I will open another issue.

Thanks for the help!
