### ISSUE TITLE
Runtime error when executing train.py

### ISSUE THREAD

**Issue by moiseshorta** [acids-ircam/ddsp_pytorch#11]
Hi,

I've been now attempting to train a custom model. So far the preprocessing works fine.

It is when I start training that I get this error:

`Traceback (most recent call last):
  File "train.py", line 79, in <module>
    y = model(p, l).squeeze(-1)
  File "/media/hexorcismos/Archivo/AI/ddsp_pytorch/ddsp_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/hexorcismos/Archivo/AI/ddsp_pytorch/ddsp/model.py", line 65, in forward
    ], -1)
RuntimeError: Sizes of tensors must match except in dimension 1. Got 375 and 400 (The offending index is 0)
`

 I also noticed that the arguments to pass into 'train.py' are different than the ones mentioned in the Readme.md. For example, there is no `--epoch` argument but rather a `--steps` arg. It maybe a good idea to update that section if it had any changes.

Thanks for your great work.

**Comment by caillonantoine** [comment]
It might be a bug coming from `crepe`, be sure to install the latest version. At some point I remember that crepe used to output different shapes depending on if it was using CPU or GPU, so if you have a GPU be sure to use it.

**Comment by moiseshorta** [comment]
I have the latest version of 'crepe==0.0.11'

It seems when executing the 'preprocessing.py' command, 'crepe' falls back to using CPU, instead of GPU...so I will try and fix my GPU libs and take it from there...

**Comment by caillonantoine** [comment]
Can you provide the yaml configuration file used for this training?

**Comment by moiseshorta** [comment]
Sure, this was my `config.yaml`:

`data:
  data_location: "/home/hexorcismos/Desktop/AI/MelGAN-VC/Datasets/ddsp_test"
  extension: "wav"

preprocess:
  sampling_rate: &samplingrate 48000
  signal_length: &signallength 192000
  block_size: &blocksize 512

  oneshot: false # crop every audio file to exactly signal length
  out_dir: ./preprocessed/

model:
  hidden_size: 512
  n_harmonic: 64
  n_bands: 65
  sampling_rate: *samplingrate
  block_size: *blocksize

train:
  scales: [4096,2048, 1024, 512, 256, 128]
  overlap: .75`

**Comment by moiseshorta** [comment]
Seems training is now working for me by changing `block_size: 512` to `block_size: 192` when at `sampling_rate: 48000`.
