### ISSUE TITLE
Pure Data example not working

### ISSUE THREAD

**Issue by Spijkervet** [acids-ircam/ddsp_pytorch#12]
Hi Antoine / IRCAM!

Fantastic work getting everything to run in real-time! I wanted to play around with the included PD patch, but found that it only produces sounds with many artefacts using your supplied pre-trained model.

I tried training on the violin audio used in the original DDSP paper, and while that appears to go well (samples sound comparable), loading the real-time converted pre-trained model gives no sound so far alas. This applies for both 16kHz and 48.

Thanks!

**Comment by moiseshorta** [comment]
Hi! I'm curious to know if you've managed to train a custom model with the provided `train.py` script... I seem to have problems when training.

**Comment by Spijkervet** [comment]
@moiseshorta I'm able to train a model, yes. I've only evaluated the output with the checkpointing that's in place - I haven't been able to reproduce it yet with offline / real-time tonetransfer code.

**Comment by caillonantoine** [comment]
Are you using the same pitch and loudness estimators for training and generation? If you want to use Sigmund in the end, you should use it as a preprocessing function too (look at the provided patches and the preprocess_from_sigmund script)

**Comment by caillonantoine** [comment]
Furthermore sigmund is far below crepe in terms of precision, so it might create artifacts too!

**Comment by Spijkervet** [comment]
> Are you using the same pitch and loudness estimators for training and generation? If you want to use Sigmund in the end, you should use it as a preprocessing function too (look at the provided patches and the preprocess_from_sigmund script)

Good point - I overlooked this. I'll make sure to convert before training with the example.pd patch, I couldn't figure out what the left-hand side of the patch was used for exactly until now.

**Comment by Spijkervet** [comment]
> Are you using the same pitch and loudness estimators for training and generation? If you want to use Sigmund in the end, you should use it as a preprocessing function too (look at the provided patches and the preprocess_from_sigmund script)

Is the supplied pre-trained weights trained on a sigmund-converted dataset? I'm not entirely sure what output to expect at the moment, it would be helpful to have a reference :)

I'll post some audio sample links once I have some samples in from the violin dataset to check.

**Comment by caillonantoine** [comment]
Yes the pretrained model is based on a sigmund preprocessing at 48kHz, I should mention it somewhere! I will post a more "clear" demo of the patch soon :)

**Comment by caillonantoine** [comment]
Commit b8bc22ffc01de8792b1160a908a77dd3d8e8da21 fixes #12
