### ISSUE TITLE
custom model training using sigmund

### ISSUE THREAD

**Issue by 303-acid** [acids-ircam/ddsp_pytorch#18]
hi antoine and ircam,

i just recently found this work, fantastic congratulations! i would like to train a custom model on a custom dataset using sigmund as preprocessor. to my understanding, i should preprocess a file using the pd patch and then running "preprocess_from_sigmund.py" before training

what confuses me is the fact that the pd patch only preprocesses one file at a time. am i therefore supposed to use only one audio file as training data? 

thank you!

mark

**Comment by 303-acid** [comment]
hi antoine and ircam,

i tried to train on a single long file. the preprocessing from pd and "preprocess_from_sigmund.py" works fine but i get the following error when i then try to start the training

`2021-04-07 14:03:34.909696: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
  0% 0/769231 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 79, in <module>
    y = model(p, l).squeeze(-1)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/ddsp_pytorch/ddsp/model.py", line 83, in forward
    amplitudes = upsample(amplitudes, self.block_size)
  File "/content/ddsp_pytorch/ddsp/core.py", line 65, in upsample
    signal = nn.functional.interpolate(signal, scale_factor=factor)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py", line 3533, in interpolate
    return torch._C._nn.upsample_nearest1d(input, output_size, scale_factors)
TypeError: upsample_nearest1d() received an invalid combination of arguments - got (Tensor, NoneType, list), but expected one of:
 * (Tensor input, tuple of ints output_size, tuple of floats scale_factors)
      didn't match because some of the arguments have invalid types: (Tensor, NoneType, list)
 * (Tensor input, tuple of ints output_size, float scales, *, Tensor out)`
 
do you know how to fix this?

thank you!

mark

**Comment by 303-acid** [comment]
using pytorch==1.7.0 fixed the problem

cheers

mark

**Comment by caillonantoine** [comment]
This error shows up for pytorch version > 1.7.1
