### ISSUE TITLE
'utils' module missed

### ISSUE THREAD

**Issue by WeiLi233** [acids-ircam/ddsp_pytorch#2]
when I modified the params and tried to run train.py, An exception throwed:
ModuleNotFoundError: No module named 'utils'

code/data.py line 10-11
```
from utils.transforms import LogTransform, NormalizeTensor, NoiseGaussian
from utils.plot import plot_batch, plot_batch_detailed
```

**Comment by esling** [comment]
Sorry for the setback @WeiLi233, we are currently reworking the overall synth architecture to make it truly modular, it should be settled by the end of this week

**Comment by esling** [comment]
We just added the missing files and updated the code, which now features a way more slick definition of the synthesizers as a simili-DAG chain.
