### ISSUE TITLE
How do I integrate this with puredata?

### ISSUE THREAD

**Issue by QuantScientist** [acids-ircam/ddsp_pytorch#20]
Hello,
Assuming I can compile this on windows, and I have the shared library, how do I load this into puredata?
I worked with JUCE in the past.

Thanks,

**Comment by caillonantoine** [comment]
Assuming you can compile it on windows, you have to specify the path of the produced library in `pd/settings/path`, and normally it should show up !

**Comment by QuantScientist** [comment]
I have the ddsp~.pd created in windows, how do I use it from pd? 
This is what I get when I open the  ddsp~.pd file:
![image](https://user-images.githubusercontent.com/18743986/122651912-753f5c00-d144-11eb-820d-b1e598ace1bc.png)
