### ISSUE TITLE
Preprocessing problem

### ISSUE THREAD

**Issue by Taikakim** [acids-ircam/ddsp_pytorch#23]
Hi, it's entirely possible that I'm understanding something wrong here, but I have a problem where the preprocessing does not work.

The included PD examples run in realtime fine with the optional pretrained models with the external I compiled. The included PD project did create a preprocessed multichannel WAV with the loudness and pitch information, but I'm not sure what to do with this since the training would still need some files that are seemingly normally generated by the preprocessing script.

I created a virtual environment where I'm trying to run the preprocess.py, but I receive this:
```

0it [00:00, ?it/s]
Traceback (most recent call last):
  File "preprocess.py", line 88, in <module>
    main()
  File "preprocess.py", line 75, in main
    signals = np.concatenate(signals, 0).astype(np.float32)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: need at least one array to concatenate
```

I have no idea where this is coming from. I have Python 3.8.8 installed, and I installed the rest of the requirements from the requirements.txt. I'm running on Ubuntu Studio 20.04

**Comment by caillonantoine** [comment]
Hi ! You should enter the path to your multichannel wav file [in the config.yaml file](https://github.com/acids-ircam/ddsp_pytorch/blob/master/config.yaml#L2) and use the `preprocess_from_sigmund.py` script instead of the regular `preprocess.py` file !
