### ISSUE TITLE
n_harmonics=100

### ISSUE THREAD

**Issue by Seungwoo0326** [acids-ircam/ddsp_pytorch#26]
According to the paper, I think the hyperparameter, model.n_harmonic should be 100 because you already project hidden dimension to n_harmonic + 1 in the harmonic part.

**Comment by caillonantoine** [comment]
You're right ! But for 16kHz audio, 100 harmonics is overkill anyway, since only signals with a fundamental frequency under 80Hz would need all of them. Furthermore I don't think it would make a great difference :)

**Comment by Seungwoo0326** [comment]
Yes, I also agree that It would not make a great difference. But it was good to know the reason why you used n_harmonic 101. Thank you for sharing your insights!

**Comment by caillonantoine** [comment]
You're welcome ☺️
