### ISSUE TITLE
Should loudness  be 20*log(abs(fft)) + A_weight ?

### ISSUE THREAD

**Issue by Teaonly** [acids-ircam/ddsp_pytorch#27]
In current code:

'''
S = np.log(abs(S) + 1e-7)
S = S + a_weight.reshape(-1, 1)
'''

the unit of A-weight should be dB, so why not S be mutipied by 20*log ?

**Comment by Teaonly** [comment]
From help document of librosa

```
amplitude_to_db(S, ref=1.0, amin=1e-05, top_db=80.0)
    Convert an amplitude spectrogram to dB-scaled spectrogram.

power_to_db(S, ref=1.0, amin=1e-10, top_db=80.0)
    Convert a power spectrogram (amplitude squared) to decibel (dB) units

    This computes the scaling ``10 * log10(S / ref)`` in a numerically
    stable way.
```

**Comment by caillonantoine** [comment]
You're right ! I been following magenta's preprocessing method to write this one, so I wasn't paying that much attention. 

But now that you mention it I wonder if it makes sense not to go back to power after applying the A weighting! I'll investigate :)

**Comment by caillonantoine** [comment]
Given that it does not affect the synthesized audio quality I close this issue !
