### ISSUE TITLE
Want to pick a licence?

### ISSUE THREAD

**Issue by bluenote10** [acids-ircam/ddsp_pytorch#36]
First of all, thanks a lot for providing this code, looks super helpful!

Since I wanted to mess around with the code a bit, I was wondering if it is possible to pick a license for the project? I'd assume without a license, forks are legally a gray area due to the default "all rights preserved".

**Comment by erl-j** [comment]
Same! I would like to use some of this code for a research project.

**Comment by caillonantoine** [comment]
I have added an Apache 2.0 License to reflect the one defined in [magenta/ddsp](https://github.com/magenta/ddsp)

**Comment by erl-j** [comment]
Thank you so much!
