### ISSUE TITLE
Tried running train.py. Some errors

### ISSUE THREAD

**Issue by muziker** [acids-ircam/ddsp_pytorch#8]
I've got this warning while running this:
  warnings.warn("Setting attributes on ParameterList is not supported.")

Also for some reason the multiscale stft sizes are a little off

stfts_orig shape : <class 'torch.Tensor'> torch.Size([54, 33, 1997])
stfts_orig shape : <class 'torch.Tensor'> torch.Size([54, 65, 997])
stfts_orig shape : <class 'torch.Tensor'> torch.Size([54, 129, 497])
stfts_orig shape : <class 'torch.Tensor'> torch.Size([54, 257, 247])
stfts_orig shape : <class 'torch.Tensor'> torch.Size([54, 513, 122])
stfts_orig shape : <class 'torch.Tensor'> torch.Size([54, 1025, 59])
stfts shape : <class 'torch.Tensor'> torch.Size([54, 33, 3997])
stfts shape : <class 'torch.Tensor'> torch.Size([54, 65, 1997])
stfts shape : <class 'torch.Tensor'> torch.Size([54, 129, 997])
stfts shape : <class 'torch.Tensor'> torch.Size([54, 257, 497])
stfts shape : <class 'torch.Tensor'> torch.Size([54, 513, 247])
stfts shape : <class 'torch.Tensor'> torch.Size([54, 1025, 122])

It would be nice to have a sample of the torchscript to try it out in pure data

**Comment by caillonantoine** [comment]
Hi,

I've restarted the project basically from scratch, everything works now !
